language: node_js
sudo: false
node_js:
  - node
install:
  - npm install -g bower
  - npm install
script:
  - bower install --production
  - npm run build
  - bower install
  - npm run example
  - pulp run

after_success:
  - >-
    test $TRAVIS_TAG &&
    echo $GITHUB_TOKEN | pulp login &&
    echo y | pulp publish --no-push
